/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

/*
 * SDK Root: /Developer/SDKs/MacOSX10.7.sdk
 */

#import <Cocoa/Cocoa.h>

@class PKBOM;

@interface PKBOMDirectoryEnumerator : NSDirectoryEnumerator
{
    PKBOM *_pkBom;
    struct _BOMBomEnumerator *_be;
    struct _BOMFSObject *_currentFSO;
}

//- (id)initWithBOM:(id)arg1;
//- (void)finalize;
//- (void)dealloc;
//- (id)nextObject;
//- (void)skipDescendants;
//- (void)skipDescendents;
//- (BOOL)isDirectory;
//- (id)fileAttributes;

@end

